databases:
  - name: send-email-db
    databaseName: send_email
    user: send_email_user
    plan: free

services:
  - type: web
    name: send-email
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: send-email-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: SITE_URL
        sync: false  # User needs to fill this after creation
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEBUG
        value: 'False'
